name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    type: [ "opened", "reopened", "synchronize" ]
  schedule:
    - cron: '0 12 * * 0'  # run once a week on Sunday
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
